### ISSUE TITLE
ModuleNotFoundError: No module named 'pygls.lsp'

### ISSUE THREAD

**Issue by barredterra** [frappe/intellisense#5]
When opening my Remote SSH Workspace (`frappe-bench` directory), I get the following error:s

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/.vscode-server/extensions/netchampfaris.frappe-intellisense-0.2.0/server/__main__.py", line 4, in <module>
    from .server import frappe_server
  File "/home/frappe/.vscode-server/extensions/netchampfaris.frappe-intellisense-0.2.0/server/server.py", line 1, in <module>
    from pygls.lsp.methods import (
ModuleNotFoundError: No module named 'pygls.lsp'
[Info  - 2:02:04 PM] Connection to server got closed. Server will restart.
####################################
# The above repeats multiple times #
####################################
[Error - 2:02:04 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by ankush** [comment]
pygls had some changes, update to pinned version in extension.

**Comment by barredterra** [comment]
```
> pip3 list | grep pygls
pygls                      0.9.1
> pip3 uninstall pygls
> pip3 install pygls==0.10.2
```

Now it works. I would, however, expect the extension to manage its dependencies itself. How can I know what version of what library it needs to work? There's no `requirements.txt` and nothing in the README.

**Comment by ankush** [comment]
The extension was updated to handle this. I don't recall facing this issue after update.

Maybe in your case it didn't update existing installed dependency.

**Comment by barredterra** [comment]
That's possible. I tried uninstalling / reinstalling without success. But let's close this issue for now.
